query getSavedCart(
  $userId: String!
  $nullOnEmpty: Boolean
  $userType: String
  $salesChannel: String
) {
  id: getSavedCart(
    userId: $userId
    nullOnEmpty: $nullOnEmpty
    userType: $userType
    salesChannel: $salesChannel
  )
}
