mutation saveCurrentCart(
  $userId: String!
  $orderFormId: String
  $userType: String
  $salesChannel: String
) {
  saveCurrentCart(
    userId: $userId
    orderFormId: $orderFormId
    userType: $userType
    salesChannel: $salesChannel
  )
}
